CREATE TABLE IF NOT EXISTS BRAND
(
	ID            SERIAL NOT NULL CONSTRAINT PK_Brand PRIMARY KEY,
	Brand_Name    VARCHAR(100) NOT NULL,
	Created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT UQ_Brand_Name UNIQUE (Brand_Name)
);

CREATE TABLE IF NOT EXISTS PROVIDER
(
	ID            SERIAL NOT NULL CONSTRAINT PK_Provider PRIMARY KEY,
	Provider_Name VARCHAR(150) NOT NULL,
    Email         VARCHAR(254) NOT NULL,
	Created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT UQ_Provider_Name UNIQUE (Provider_Name),
    CONSTRAINT UQ_Email UNIQUE (Email)
);

CREATE TABLE IF NOT EXISTS PROVIDER_TEMPLATE
(
	ID            SERIAL NOT NULL CONSTRAINT PK_ProviderTemplate PRIMARY KEY,
	ID_Provider   INT NOT NULL,
    Template_Name VARCHAR(100) NOT NULL,
    Mail_Template TEXT,
	Created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT UQ_ProviderTemplate_Name UNIQUE (ID_Provider,Template_Name),
	CONSTRAINT FK_ProviderTemplate FOREIGN KEY (ID_Provider) REFERENCES PROVIDER(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUCT
(
	ID            SERIAL NOT NULL CONSTRAINT PK_Product PRIMARY KEY,
	Product_Name  VARCHAR(200) NOT NULL,
    Serial_Number VARCHAR(100) NOT NULL,
    ID_Brand      INT NOT NULL,
	Created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT UQ_SerialNumber UNIQUE (Serial_Number),
    CONSTRAINT FK_ProductBrand FOREIGN KEY (ID_Brand) REFERENCES BRAND(ID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS PRODUCT_PROVIDER
(
	ID_Product    INT NOT NULL,
    ID_Provider   INT NOT NULL,
	Created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT PK_ProductProvider PRIMARY KEY (ID_Product, ID_Provider),
    CONSTRAINT FK_ProviderProduct FOREIGN KEY (ID_Product) REFERENCES PRODUCT(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ProductProvider FOREIGN KEY (ID_Provider) REFERENCES PROVIDER(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUCT_FILE
(
	ID            SERIAL NOT NULL CONSTRAINT PK_ProductFile PRIMARY KEY,
	ID_Product    INT NOT NULL,
    File_Type     VARCHAR(10) NOT NULL,
    File_Path     TEXT NOT NULL,
	Created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_ProductFile FOREIGN KEY (ID_Product) REFERENCES PRODUCT(ID) ON DELETE CASCADE
	CONSTRAINT UQ_FilePath UNIQUE (File_Path)
);

CREATE TABLE IF NOT EXISTS SENT
(
	ID             SERIAL NOT NULL CONSTRAINT PK_Sent PRIMARY KEY,
	ID_Product     INT NOT NULL,
    ID_Provider    INT NOT NULL,
    Provider_Email VARCHAR(254) NOT NULL,
    Invoice        VARCHAR(100) NOT NULL,
    Case_Type      VARCHAR(10) NOT NULL,
	Subject_Email  VARCHAR(300) NOT NULL,
    Body_Content   TEXT NOT NULL,
	Created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_ProductSent FOREIGN KEY (ID_Product) REFERENCES PRODUCT(ID) ON DELETE RESTRICT,
    CONSTRAINT FK_ProvidertSent FOREIGN KEY (ID_Provider) REFERENCES PROVIDER(ID) ON DELETE RESTRICT
);